stages:
  data_ingestion:
    cmd: python src/BoxOfficePrediction/pipeline/stage01_data_ingestion.py
    deps: 
      - src/BoxOfficePrediction/components/data_ingestion.py
    outs :
      - artifacts/data_ingestion/tmdb_5000_credits.csv
      - artifacts/data_ingestion/tmdb_5000_movies.csv
      - artifacts/data_ingestion/ticket_prices.csv

  data_organize:
    cmd: python src/BoxOfficePrediction/pipeline/stage02_data_organize.py
    deps:
      - src/BoxOfficePrediction/components/data_organize.py
      - artifacts/data_ingestion/ticket_prices.csv
      - artifacts/data_ingestion/tmdb_5000_credits.csv
      - artifacts/data_ingestion/tmdb_5000_movies.csv
    outs:
      - artifacts/data_transform/organized_cinema.csv

  data_validation:
    cmd: python src/BoxOfficePrediction/pipeline/stage_data_validatioin.py
    deps:
      - src/BoxOfficePrediction/components/data_validation.py
      - schema.yaml
    outs:
      - artifacts/data_validation/status.txt
  
  feature_engineering:
    cmd : python src/BoxOfficePrediction/pipeline/stage03_feature_engineering.py
    deps :
      - src/BoxOfficePrediction/components/feature_engineering.py
      - artifacts/data_transform/organized_cinema.csv
    outs:
      - artifacts/data_scores/director_score.csv
      - artifacts/data_scores/hero_score.csv
      - artifacts/data_scores/heroine_score.csv
      - artifacts/data_transform/train.csv
      - artifacts/data_transform/test.csv

  model_training:
    cmd: python src/BoxOfficePrediction/pipeline/stage05_model_training.py
    deps:
      - src/BoxOfficePrediction/components/model_training.py
      - src/BoxOfficePrediction/pipeline/stage04_data_preprocessing.py
      - params.yaml
    outs:
      - models/preprocessor.pkl
      - models/RandomForest_model.pkl
      - models/DecisionTree_model.pkl
      - models/GradientBoosting_model.pkl
      - models/LinearRegression_model.pkl
      - models/XGBoost_model.pkl
      - models/CatBoost_model.pkl
      - models/AdaBoost_model.pkl

  model_evaluation :
    cmd : python src/BoxOfficePrediction/pipeline/stage06_model_evaluation.py
    deps :
      - src/BoxOfficePrediction/components/model_evaluation.py
      - models/best_params.yaml
