artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: tmdb/tmdb-movie-metadata
  ticket_price_dataset_link : https://docs.google.com/spreadsheets/d/e/2PACX-1vSit8SB8zhzoRkcdCpOnTNgatlFQFb6FqG_IabDTcJ66nEPx_36bE2UR4ck-fiXWFsMVmqUpodTbcxL/pub?gid=0&single=true&output=csv
  ticket_price_file : artifacts/data_ingestion/ticket_prices.csv
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion

data_organize:
  movie_table_path: artifacts/data_ingestion/tmdb_5000_movies.csv
  credit_table_path: artifacts/data_ingestion/tmdb_5000_credits.csv
  ticket_price_table_path : artifacts/data_ingestion/ticket_prices.csv
  org_table_path: artifacts/data_transform

data_validation:
  root_dir : artifacts/data_validation
  val_data_path : artifacts/data_transform/organized_cinema.csv
  status_file : artifacts/data_validation/status.txt

feature_engineering:
  organized_data : artifacts/data_transform/organized_cinema.csv
  featured_data : artifacts/data_transform
  scores_data : artifacts/data_scores

data_preprocessing:
  root_dir: models

model_training :
  train_data : artifacts/data_transform/train.csv
  preprocessor_path : models/preprocessor.pkl
  model_path : models
  
model_evaluation :
  test_data : artifacts/data_transform/test.csv
  preprocessor_path : models/preprocessor.pkl
  best_params_path : models/best_params.yaml
  Adaboost : models/AdaBoost_model.pkl
  CatBoost : models/CatBoost_model.pkl
  DscisionTree : models/DecisionTree_model.pkl
  GradientBoosting : models/GradientBoosting_model.pkl
  LinearRegression : models/LinearRegression_model.pkl
  RandomForest : models/RandomForest_model.pkl
  XGBoost : models/XGBoost_model.pkl
  mlflow_uri : https://dagshub.com/uvaishnav/BoxOfficePrediction.mlflow

prediction_pipeline:
  preprocessor_path : models/preprocessor.pkl
  model_path : models/XGBoost_model.pkl
  