AdaBoost:
  learning_rate: 0.01
  n_estimators: 281
CatBoost:
  depth: 6
  iterations: 663
  learning_rate: 0.01
DecisionTree:
  max_depth: 5
  min_samples_leaf: 3
  min_samples_split: 9
GradientBoosting:
  learning_rate: 0.01
  max_depth: 6
  n_estimators: 408
LinearRegression:
  fit_intercept: true
RandomForest:
  max_depth: 9
  min_samples_leaf: 2
  min_samples_split: 16
  n_estimators: 986
XGBoost:
  colsample_bytree: 0.9
  learning_rate: 0.01
  max_depth: 5
  n_estimators: 368
