AdaBoost:
  learning_rate: 0.11
  n_estimators: 432
CatBoost:
  depth: 5
  iterations: 826
  learning_rate: 0.01
DecisionTree:
  max_depth: 6
  min_samples_leaf: 4
  min_samples_split: 4
GradientBoosting:
  learning_rate: 0.01
  max_depth: 8
  n_estimators: 957
LinearRegression:
  fit_intercept: false
RandomForest:
  max_depth: 8
  min_samples_leaf: 1
  min_samples_split: 15
  n_estimators: 447
XGBoost:
  colsample_bytree: 0.30000000000000004
  learning_rate: 0.11
  max_depth: 4
  n_estimators: 444
