AdaBoost:
  learning_rate: 0.21000000000000002
  n_estimators: 115
CatBoost:
  depth: 5
  iterations: 730
  learning_rate: 0.11
DecisionTree:
  max_depth: 5
  min_samples_leaf: 5
  min_samples_split: 5
GradientBoosting:
  learning_rate: 0.11
  max_depth: 5
  n_estimators: 139
LinearRegression:
  fit_intercept: false
RandomForest:
  max_depth: 7
  min_samples_leaf: 6
  min_samples_split: 18
  n_estimators: 508
XGBoost:
  colsample_bytree: 0.8
  learning_rate: 0.11
  max_depth: 7
  n_estimators: 622
