AdaBoost:
  learning_rate: 0.01
  n_estimators: 138
CatBoost:
  depth: 5
  iterations: 814
  learning_rate: 0.01
DecisionTree:
  max_depth: 6
  min_samples_leaf: 4
  min_samples_split: 19
GradientBoosting:
  learning_rate: 0.01
  max_depth: 7
  n_estimators: 389
LinearRegression:
  fit_intercept: true
RandomForest:
  max_depth: 9
  min_samples_leaf: 3
  min_samples_split: 11
  n_estimators: 855
XGBoost:
  colsample_bytree: 0.4
  learning_rate: 0.01
  max_depth: 6
  n_estimators: 558
